services:
  sysbench-android-build:
    build:
      context: .
      dockerfile: Dockerfile
      
      args:
        SYSBENCH_REF: master
    image: sysbench-android-builder:latest
    volumes:
      - ./out:/out
      - ./build-sysbench-android.sh:/work/build-sysbench-android.sh:ro
      - ./src:/work/src:ro
    environment:
      - JOBS=
      - OUT_DIR=/out
    command: ["/bin/bash", "/work/build-sysbench-android.sh"]
